// source: cpu_softirq.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

// var jspb = require('google-protobuf');
import * as jspb from 'google-protobuf';
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.monitor.proto.SoftIrq', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.monitor.proto.SoftIrq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.monitor.proto.SoftIrq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.monitor.proto.SoftIrq.displayName = 'proto.monitor.proto.SoftIrq';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.monitor.proto.SoftIrq.prototype.toObject = function(opt_includeInstance) {
  return proto.monitor.proto.SoftIrq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.monitor.proto.SoftIrq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.monitor.proto.SoftIrq.toObject = function(includeInstance, msg) {
  var f, obj = {
    cpu: jspb.Message.getFieldWithDefault(msg, 1, ""),
    hi: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    timer: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    netTx: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    netRx: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    block: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    irqPoll: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
    tasklet: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0),
    sched: jspb.Message.getFloatingPointFieldWithDefault(msg, 9, 0.0),
    hrtimer: jspb.Message.getFloatingPointFieldWithDefault(msg, 10, 0.0),
    rcu: jspb.Message.getFloatingPointFieldWithDefault(msg, 11, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.monitor.proto.SoftIrq}
 */
proto.monitor.proto.SoftIrq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.monitor.proto.SoftIrq;
  return proto.monitor.proto.SoftIrq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.monitor.proto.SoftIrq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.monitor.proto.SoftIrq}
 */
proto.monitor.proto.SoftIrq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCpu(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setHi(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setTimer(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setNetTx(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setNetRx(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setBlock(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setIrqPoll(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setTasklet(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setSched(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setHrtimer(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setRcu(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.monitor.proto.SoftIrq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.monitor.proto.SoftIrq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.monitor.proto.SoftIrq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.monitor.proto.SoftIrq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCpu();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getHi();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getTimer();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getNetTx();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = message.getNetRx();
  if (f !== 0.0) {
    writer.writeFloat(
      5,
      f
    );
  }
  f = message.getBlock();
  if (f !== 0.0) {
    writer.writeFloat(
      6,
      f
    );
  }
  f = message.getIrqPoll();
  if (f !== 0.0) {
    writer.writeFloat(
      7,
      f
    );
  }
  f = message.getTasklet();
  if (f !== 0.0) {
    writer.writeFloat(
      8,
      f
    );
  }
  f = message.getSched();
  if (f !== 0.0) {
    writer.writeFloat(
      9,
      f
    );
  }
  f = message.getHrtimer();
  if (f !== 0.0) {
    writer.writeFloat(
      10,
      f
    );
  }
  f = message.getRcu();
  if (f !== 0.0) {
    writer.writeFloat(
      11,
      f
    );
  }
};


/**
 * optional string cpu = 1;
 * @return {string}
 */
proto.monitor.proto.SoftIrq.prototype.getCpu = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.monitor.proto.SoftIrq} returns this
 */
proto.monitor.proto.SoftIrq.prototype.setCpu = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional float hi = 2;
 * @return {number}
 */
proto.monitor.proto.SoftIrq.prototype.getHi = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.monitor.proto.SoftIrq} returns this
 */
proto.monitor.proto.SoftIrq.prototype.setHi = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional float timer = 3;
 * @return {number}
 */
proto.monitor.proto.SoftIrq.prototype.getTimer = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.monitor.proto.SoftIrq} returns this
 */
proto.monitor.proto.SoftIrq.prototype.setTimer = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional float net_tx = 4;
 * @return {number}
 */
proto.monitor.proto.SoftIrq.prototype.getNetTx = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.monitor.proto.SoftIrq} returns this
 */
proto.monitor.proto.SoftIrq.prototype.setNetTx = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional float net_rx = 5;
 * @return {number}
 */
proto.monitor.proto.SoftIrq.prototype.getNetRx = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.monitor.proto.SoftIrq} returns this
 */
proto.monitor.proto.SoftIrq.prototype.setNetRx = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional float block = 6;
 * @return {number}
 */
proto.monitor.proto.SoftIrq.prototype.getBlock = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.monitor.proto.SoftIrq} returns this
 */
proto.monitor.proto.SoftIrq.prototype.setBlock = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional float irq_poll = 7;
 * @return {number}
 */
proto.monitor.proto.SoftIrq.prototype.getIrqPoll = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.monitor.proto.SoftIrq} returns this
 */
proto.monitor.proto.SoftIrq.prototype.setIrqPoll = function(value) {
  return jspb.Message.setProto3FloatField(this, 7, value);
};


/**
 * optional float tasklet = 8;
 * @return {number}
 */
proto.monitor.proto.SoftIrq.prototype.getTasklet = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.monitor.proto.SoftIrq} returns this
 */
proto.monitor.proto.SoftIrq.prototype.setTasklet = function(value) {
  return jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * optional float sched = 9;
 * @return {number}
 */
proto.monitor.proto.SoftIrq.prototype.getSched = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 9, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.monitor.proto.SoftIrq} returns this
 */
proto.monitor.proto.SoftIrq.prototype.setSched = function(value) {
  return jspb.Message.setProto3FloatField(this, 9, value);
};


/**
 * optional float hrtimer = 10;
 * @return {number}
 */
proto.monitor.proto.SoftIrq.prototype.getHrtimer = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 10, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.monitor.proto.SoftIrq} returns this
 */
proto.monitor.proto.SoftIrq.prototype.setHrtimer = function(value) {
  return jspb.Message.setProto3FloatField(this, 10, value);
};


/**
 * optional float rcu = 11;
 * @return {number}
 */
proto.monitor.proto.SoftIrq.prototype.getRcu = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 11, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.monitor.proto.SoftIrq} returns this
 */
proto.monitor.proto.SoftIrq.prototype.setRcu = function(value) {
  return jspb.Message.setProto3FloatField(this, 11, value);
};


// goog.object.extend(exports, proto.monitor.proto);
export const SoftIrq = proto.monitor.proto.SoftIrq;