// source: cpu_stat.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

// var jspb = require('google-protobuf');
import * as jspb from 'google-protobuf';
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.monitor.proto.CpuStat', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.monitor.proto.CpuStat = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.monitor.proto.CpuStat, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.monitor.proto.CpuStat.displayName = 'proto.monitor.proto.CpuStat';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.monitor.proto.CpuStat.prototype.toObject = function(opt_includeInstance) {
  return proto.monitor.proto.CpuStat.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.monitor.proto.CpuStat} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.monitor.proto.CpuStat.toObject = function(includeInstance, msg) {
  var f, obj = {
    cpuName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    cpuPercent: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    usrPercent: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    systemPercent: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    nicePercent: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    idlePercent: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    ioWaitPercent: jspb.Message.getFloatingPointFieldWithDefault(msg, 7, 0.0),
    irqPercent: jspb.Message.getFloatingPointFieldWithDefault(msg, 8, 0.0),
    softIrqPercent: jspb.Message.getFloatingPointFieldWithDefault(msg, 9, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.monitor.proto.CpuStat}
 */
proto.monitor.proto.CpuStat.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.monitor.proto.CpuStat;
  return proto.monitor.proto.CpuStat.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.monitor.proto.CpuStat} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.monitor.proto.CpuStat}
 */
proto.monitor.proto.CpuStat.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCpuName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setCpuPercent(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setUsrPercent(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setSystemPercent(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setNicePercent(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setIdlePercent(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setIoWaitPercent(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setIrqPercent(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setSoftIrqPercent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.monitor.proto.CpuStat.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.monitor.proto.CpuStat.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.monitor.proto.CpuStat} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.monitor.proto.CpuStat.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCpuName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getCpuPercent();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getUsrPercent();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getSystemPercent();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = message.getNicePercent();
  if (f !== 0.0) {
    writer.writeFloat(
      5,
      f
    );
  }
  f = message.getIdlePercent();
  if (f !== 0.0) {
    writer.writeFloat(
      6,
      f
    );
  }
  f = message.getIoWaitPercent();
  if (f !== 0.0) {
    writer.writeFloat(
      7,
      f
    );
  }
  f = message.getIrqPercent();
  if (f !== 0.0) {
    writer.writeFloat(
      8,
      f
    );
  }
  f = message.getSoftIrqPercent();
  if (f !== 0.0) {
    writer.writeFloat(
      9,
      f
    );
  }
};


/**
 * optional string cpu_name = 1;
 * @return {string}
 */
proto.monitor.proto.CpuStat.prototype.getCpuName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.monitor.proto.CpuStat} returns this
 */
proto.monitor.proto.CpuStat.prototype.setCpuName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional float cpu_percent = 2;
 * @return {number}
 */
proto.monitor.proto.CpuStat.prototype.getCpuPercent = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.monitor.proto.CpuStat} returns this
 */
proto.monitor.proto.CpuStat.prototype.setCpuPercent = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional float usr_percent = 3;
 * @return {number}
 */
proto.monitor.proto.CpuStat.prototype.getUsrPercent = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.monitor.proto.CpuStat} returns this
 */
proto.monitor.proto.CpuStat.prototype.setUsrPercent = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional float system_percent = 4;
 * @return {number}
 */
proto.monitor.proto.CpuStat.prototype.getSystemPercent = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.monitor.proto.CpuStat} returns this
 */
proto.monitor.proto.CpuStat.prototype.setSystemPercent = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional float nice_percent = 5;
 * @return {number}
 */
proto.monitor.proto.CpuStat.prototype.getNicePercent = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.monitor.proto.CpuStat} returns this
 */
proto.monitor.proto.CpuStat.prototype.setNicePercent = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional float idle_percent = 6;
 * @return {number}
 */
proto.monitor.proto.CpuStat.prototype.getIdlePercent = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.monitor.proto.CpuStat} returns this
 */
proto.monitor.proto.CpuStat.prototype.setIdlePercent = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional float io_wait_percent = 7;
 * @return {number}
 */
proto.monitor.proto.CpuStat.prototype.getIoWaitPercent = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.monitor.proto.CpuStat} returns this
 */
proto.monitor.proto.CpuStat.prototype.setIoWaitPercent = function(value) {
  return jspb.Message.setProto3FloatField(this, 7, value);
};


/**
 * optional float irq_percent = 8;
 * @return {number}
 */
proto.monitor.proto.CpuStat.prototype.getIrqPercent = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 8, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.monitor.proto.CpuStat} returns this
 */
proto.monitor.proto.CpuStat.prototype.setIrqPercent = function(value) {
  return jspb.Message.setProto3FloatField(this, 8, value);
};


/**
 * optional float soft_irq_percent = 9;
 * @return {number}
 */
proto.monitor.proto.CpuStat.prototype.getSoftIrqPercent = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 9, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.monitor.proto.CpuStat} returns this
 */
proto.monitor.proto.CpuStat.prototype.setSoftIrqPercent = function(value) {
  return jspb.Message.setProto3FloatField(this, 9, value);
};


// goog.object.extend(exports, proto.monitor.proto);
export const CpuStat = proto.monitor.proto.CpuStat;
